CREATE TABLE todolist (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    task VARCHAR(255) NOT NULL,
    memo VARCHAR(255) NOT NULL,
    deadline DATETIME NOT NULL,
    importance INTEGER NOT NULL,
    done BOOLEAN NOT NULL DEFAULT FALSE
);